[package]
name = "gawain"
version = "0.1.0"
edition = "2021"
authors = ["Matt Gaughan"]
description = "A package to gather data from software repositories, quickly."
readme = "README.md"

[dependencies]
git2 = "0.19.0"
